### PR TITLE
Add by: {:conn, func} option

### PR DESCRIPTION
**Pull request by blatyo**
I'm interested in using this for rate limiting login attempts. However, I want to rate limit on the email that's in the request parameters, which none of the by options currently support.

### CODE REVIEW

**Comment by ShaneKilkelly** [comment]
This change makes a lot of sense, thanks!

Would you mind adding a small test to `/test/hammer_plug_test.exs`? You could use the `:session, func` test as a guideline: https://github.com/ExHammer/hammer-plug/blob/master/test/hammer_plug_test.exs#L114

**Comment by blatyo** [comment]
Yea, I can add one. I tried running them yesterday, but couldn't get them to run.

**Comment by blatyo** [comment]
Added the tests. I had to add config for hammer, because it was crashing, complaining that no `:expiry_ms` was set. I also had to upgrade `mock`, because I was getting compilation errors otherwise.

**Comment by ShaneKilkelly** [comment]
Interesting, did you run the tests with `make test` ? I think that should run the tests without the need for configuration (at least it works locally for me).

I think the difference is that `make test` calls `mix test` with the `--no-start` flag, which skips starting the `Hammer` app.

**Comment by ShaneKilkelly** [comment]
Either way, this looks good, I'll merge and deploy in the next day or so. Thanks! :tada:

**Comment by blatyo** [comment]
I didn't even realize there was a makefile. I was running it with `mix test`

**Comment by ShaneKilkelly** [comment]
I'll merge this today and publish a new version asap :)

**Comment by ShaneKilkelly** [comment]
Done, published as version 2.1

**Comment by blatyo** [comment]
thanks

**Pull request merged**
